### PR TITLE
capi: make opaque types an exact size and alignment

### LINKED ISSUE #227: capi: opaque size mismatch causes slice issues
We assumed a larger size for an opaque type would be fine since the real type would fit inside. This doesn't work when using the opaque type in a slice, since the stride does not match between C and Rust.

If we make the `opaque` macro require exact size/alignment, then we will need many `cfg_attr`s for different platforms/configurations.

Suggested fix: pad the Rust type to fit the declared size/align.

### PR DESCRIPTION
**Pull request by jdygert-spok**
The opaque macro now serves two functions. It first wraps the original type in the `Opaque` wrapper. Then it applies the `[u8; SIZE]` representation to the generated renamed type that cbindgen sees.

Closes #227.

### CODE REVIEW

File: crates/aranya-capi-macro/src/opaque.rs [hunk 1]
```diff
@@ -1,70 +1,86 @@
...
-        Item::Struct(s) => (&s.vis, &s.ident, &s.attrs),
-        Item::Type(t) => (&t.vis, &t.ident, &t.attrs),
-        item => {
-            return Err(Error::new_spanned(
-                item,
-                "`#[capi::opaque]` can only be applied to `struct`s",
-            ))
-        }
+    let Item::Type(mut t) = item else {
+        // TODO(jdygert): Allow structs again?
```
Comment (ssweetney-spok) [inline crates/aranya-capi-macro/src/opaque.rs:23]: Should the doc comment in "crates/aranya-capi-codegen/src/syntax/opaque.rs" be updated?

File: crates/aranya-capi-core/src/opaque.rs [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+
+    #[repr(C)]
+    pub(super) union OpaqueRepr<const SIZE: usize, const ALIGN: usize, T>
+    where
+        elain::Align<ALIGN>: elain::Alignment,
+    {
+        // Invariant: always the `inner` variant.
+        // Invariant: only dropped in the drop impl.
+        inner: ManuallyDrop<T>,
+        __backing_for_size_align_only: Backing<SIZE, ALIGN>,
```
Comment (ssweetney-spok) [inline crates/aranya-capi-core/src/opaque.rs:22]: Can you explain how this works? Shouldn't the size of `T` be used to determine how much padding is needed to get the specified size and alignment?

Comment (ssweetney-spok) [reply crates/aranya-capi-core/src/opaque.rs:22]: Just now realized this is a union not a struct 🤦. It makes sense now

**Review by ssweetney-spok — APPROVED** [review]
Looks great! I found this approach really interesting

Very minor nit: The usage of `core::convert::Infallible` confused me at first. It might make things easier to understand by defining an enum with no variants and adding some doc comments that explain that it only exists to prevent a `Backing` from being constructed

**Review by elagergren-spideroak — APPROVED** [review]
Much better. Thanks.
