### PR TITLE
Fix #447: Require policy block in command.

### LINKED ISSUE #447: Command compiles without policy block
This compiles when it shouldn't:
```
    command Cmd {
        fields {}
        seal { return todo() }
        open { return todo() }
}
```
Compilation should fail with something like "command requires policy block".

### PR DESCRIPTION
**Pull request by apetkov-so**
- Require a command to have a `policy` block
- Enforce order of command blocks

### CODE REVIEW

**Comment by apetkov-so** [comment]
There's a follow up ticket for duplicate blocks: https://github.com/aranya-project/aranya-core/issues/450

**Review by ssweetney-spok — COMMENTED** [review]
I didn't realize omitting the policy block was possible... good catch.

How do we want to handle this? As is, you could still write

```
policy {
    let num = 1
}
```

which seems as useful as an empty/missing policy block.

Edit: We do similar checks for the seal/open blocks so this should be OK

File: crates/aranya-policy-compiler/src/tests.rs [hunk 1]
```diff
@@ -1902,6 +1959,8 @@ fn test_type_errors() {
         Case {
             t: r#"
                 command Foo {
+                    seal { return todo() }
```
[the remark this answers is not in the document]
Comment (jdygert-spok) [reply crates/aranya-policy-compiler/src/tests.rs]: The policy block is compiled first, and we don't check for the seal block until we try to compile it.

**Review by ssweetney-spok — DISMISSED** [review]

**Comment by apetkov-so** [comment]
> ... which seems as useful as an empty/missing policy block.

We could add a command analyzer to the tracer, that would ensure there's a finish block, and a least one publish.

**Comment by chip-so** [comment]
> We could add a command analyzer to the tracer, that would ensure there's a finish block, and a least one publish.

We already have the [FinishAnalyzer](https://github.com/aranya-project/aranya-core/blob/main/crates/aranya-policy-compiler/src/tracer/analyzers/finish_analyzer.rs).

**Review by chip-so — DISMISSED** [review]

**Comment by chip-so** [comment]
> How do we feel about changing the pest rule to require a certain order?

I guess that's fine but it also seems unimportant.

**Comment by jdygert-spok** [comment]
> > How do we feel about changing the pest rule to require a certain order?
> 
> I guess that's fine but it also seems unimportant.

I ask because it solves this issue and #450 in a simpler way.

File: crates/aranya-policy-lang/src/lang/parse/tests.rs
[the remark this answers is not in the document]
Comment (apetkov-so) [reply crates/aranya-policy-lang/src/lang/parse/tests.rs]: Ugh, merge hell. Let me go figure out what got moved and where.

File: crates/aranya-policy-lang/tests/data/command_attributes.snap
Comment (ssweetney-spok) [inline crates/aranya-policy-lang/tests/data/command_attributes.snap]: This test and the other ones that became errors should probably be updated to have the missing blocks then a create separate test to show this error (due to missing the blocks).

The attribute parsing this is supposed to test isn't present in "tictactoe.md" so it'd be good to test it

Comment (apetkov-so) [reply crates/aranya-policy-lang/tests/data/command_attributes.snap]: But the new tests would then be error tests, no?

Comment (ssweetney-spok) [reply crates/aranya-policy-lang/tests/data/command_attributes.snap]: Yea, I was thinking that there would be just one new test (not multiple) to show the "expected fields_block or seal_block" error.

This file shouldn't be an error though since we still want to have a test to demonstrate that parsing attributes works as expected.

**Review by chip-so — COMMENTED** [review]
I guess this is fine, but I don't love that this turns a missing block into a syntax error. Pest Syntax errors are the worst kind of errors we produce, and are unfortunately opaque about what you need to do to fix them.

**Review by chip-so — DISMISSED** [review]

File: crates/aranya-policy-lang/tests/data/policy_test.snap
Comment (ssweetney-spok) [inline crates/aranya-policy-lang/tests/data/policy_test.snap]: This is outputting an error again. It looks like there's a missing block in `crates/aranya-policy-lang/tests/data/policy_test.policy` somewhere

**Review by ssweetney-spok — COMMENTED** [review]
LGTM. Just some small comments left

File: crates/aranya-policy-lang/tests/data/policy_test.snap
Comment (apetkov-so) [reply crates/aranya-policy-lang/tests/data/policy_test.snap]: What do you mean? The tests pass.

File: crates/aranya-policy-lang/tests/data/seal_open.snap
Comment (jdygert-spok) [inline crates/aranya-policy-lang/tests/data/seal_open.snap]: Probably want to add policy block to make this one pass again

Comment (jdygert-spok) [reply crates/aranya-policy-lang/tests/data/seal_open.snap]: Might be a redundant test at this point though.

**Review by chip-so — APPROVED** [review]
