### PR TITLE
afc: add `SealCtx` to fix `Seq` tracking

### LINKED ISSUE #422: afc: shm doesn't properly record sequence number
When performing a seal, the sequence number for that channel is incremented. In short, this is only written to the "read" side of the list.

### PR DESCRIPTION
**Pull request by jdygert-spok**
Fixes #422 with minimal changes by changing seal to take a mutable context.

### CODE REVIEW

File: crates/aranya-fast-channels/benches/lib.rs [hunk 1]
```diff
@@ -169,12 +176,12 @@ macro_rules! bench_impl {
...
 				// never cached.
-				let mut iter = chans.iter().cycle().copied();
+				let mut iter = chans.iter_mut();
 				g.bench_function(BenchmarkId::new("seal_miss", *size), |b| {
-					let (seal_channel_id, _) = iter.next().expect("should repeat");
+                    let (seal_ctx, _) = iter.next().expect("not enough channels");
 					b.iter(|| {
 						black_box(client.seal(
-							black_box(seal_channel_id),
+							black_box(seal_ctx),
```
[the remark this answers is not in the document]
Comment (jdygert-spok) [reply crates/aranya-fast-channels/benches/lib.rs]: Yeah, we also should distinguish the benchmark cases of whether the channel moves to a different index. I don't think it's really worth fixing right now. Unsure whether to keep the benchmark the same to show that this specific case has improved since there's essentially a cache for every seal now.

**Review by ssweetney-spok — DISMISSED** [review]

File: crates/aranya-fast-channels/src/client.rs [hunk 2]
```diff
@@ -148,10 +156,10 @@ impl<S: AfcState> Client<S> {
             /* ad: */ &AuthData,
         ) -> Result<Seq, Error>,
     {
-        debug!("finding seal info: id={id}");
+        // debug!("finding seal info: id={id}");
 
-        let seq = self.state.seal(id, |aead, label_id| {
-            debug!("encrypting id={id}");
+        let seq = self.state.seal(ctx, |aead, label_id| {
+            // debug!("encrypting id={id}");
```
Comment (gknopf-aranya) [inline crates/aranya-fast-channels/src/client.rs]: Remove this?

File: crates/aranya-fast-channels/src/client.rs [hunk 3]
```diff
@@ -53,14 +53,22 @@ impl<S: AfcState> Client<S> {
         v
     }
 
+    /// Set up the seal context for the given channel.
+    ///
+    /// This must only be called once for any given ID. Failure to
+    /// do so will result in repeated sequence numbers.
```
Comment (gknopf-aranya) [inline crates/aranya-fast-channels/src/client.rs]:
```suggestion
    /// This must only be called once for any given channel ID. Failure to
    /// do so will result in repeated sequence numbers (a.k.a. a repeated nonce).
```
What is the consequence of a repeated nonce in this case? Does it leak the key or plaintext? Does it make us vulnerable to a chosen plaintext/ciphertext attack? May be worth documenting the risk here.

**Review by gknopf-aranya — DISMISSED** [review]

**Review by gknopf-aranya — APPROVED** [review]
